FROM tiger0421/ros-gpu-gazebo:1.0-glvnd-runtime-ubuntu18.04

WORKDIR /root/catkin_ws
RUN echo "source /opt/ros/melodic/setup.bash" >> ~/.bashrc && \
    bash -c "source ~/.bashrc" && \
    mkdir src && \
    catkin init && \
    rm /bin/sh && \
    ln -s /bin/bash /bin/sh

WORKDIR /root/catkin_ws/src

RUN apt update && \
    apt upgrade -y && \
    wget https://raw.githubusercontent.com/open-rdc/orne_navigation/melodic-devel/orne_pkgs.install && \
    git clone https://github.com/openspur/yp-spur.git && \
    wstool init && \
    wstool merge orne_pkgs.install && \
    wstool up \
    && \
    source /opt/ros/melodic/setup.bash && \
    cd /root/catkin_ws && \
    rosdep init && \
    rosdep update && \
    rosdep install --from-paths src/ --ignore-src --rosdistro $ROS_DISTRO -y && \
    export CMAKE_PREFIX_PATH=~/catkin_ws/devel:/opt/ros/$ROS_DISTRO && \
    apt autoremove -y && \
    apt clean && \
    rm -rf /var/lib/apt/lists/*

RUN source /opt/ros/melodic/setup.bash && \
catkin build && \
echo "source ~/catkin_ws/devel/setup.bash" >> ~/.bashrc

WORKDIR /root
CMD /bin/bash
